### ISSUE TITLE
Create HTML + email templates

### ISSUE THREAD

**Issue by enkore** [Qabel/qabel-index#15]
Templates for web pages and emails are missing or incomplete.

**Comment by jmt85** [comment]
can you give me the links and name the emails?

**Comment by enkore** [comment]
The incomplete email template: https://github.com/Qabel/qabel-register/blob/master/register_service/templates/verification/email.tpl

These shall be made similar in wording/appearance to the [account registration mails](https://github.com/Qabel/qabel-accounting/tree/master/qabel_provider/templates/account/email) I think.

The missing template(s) for verification page in browser: https://github.com/Qabel/qabel-register/blob/master/register_service/verification.py#L91

**Comment by mr-gosh** [comment]
given the present mail (including the typos ;) )
i generated a simple formatted html mail:
![account registration schlicht](https://cloud.githubusercontent.com/assets/3028703/17406336/45751058-5a63-11e6-9c52-ecfd615e6d16.png)

i created a slightly enhanced version from that:
![html-mail-accountregistration](https://cloud.githubusercontent.com/assets/3028703/17406348/5a67e7b0-5a63-11e6-809b-28952bba0d12.png)

which version should we use and which text should be integrated?

**Comment by mr-gosh** [comment]
perhaps we should user something like this for the formatting:
http://webdesign.tutsplus.com/de/articles/creating-a-simple-responsive-html-email--webdesign-12978

and i will create a text-only version of the above... html stuff

**Comment by mr-gosh** [comment]
@enkore what do you think - is such a "responsive" html template a good solution?

**Comment by enkore** [comment]
Yes, I think it makes sense

**Comment by jmt85** [comment]
how is the state of this issue?
