### ISSUE TITLE
Local host names are rejected in drop URLs

### ISSUE THREAD

**Issue by enkore** [Qabel/qabel-index#45]
For example `http://compuglobalhypermeganet:5000/APDIQ_X-OQVZuNp_4D3mNi5pvF0Y9G1cSfqWn-u6-uQ` is rejected, while `http://localhost:5000/APDIQ_X-OQVZuNp_4D3mNi5pvF0Y9G1cSfqWn-u6-uQ` would be considered invalid (`http://localhorst` is also invalid).

This is an issue with DRF3 URLField, which usees Django's URLValidator, where this behaviour is known and seems to be intentional: https://code.djangoproject.com/ticket/25418

By the way - we can and probably should validate that it's actually a drop URL according to the drop spec.

**Comment by enkore** [comment]
This generally does not impact production systems.

Fix was deployed to TC.

**Comment by thechauffeur** [comment]
> By the way - we can and probably should validate that it's actually a drop URL according to the drop spec.

👍 We have spec -- we should validate against it.

**Comment by enkore** [comment]
= #46

**Comment by enkore** [comment]
def resolution := document in q.gh.io spec.
